# Generated by Django 4.1.6 on 2023-02-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geo',
            name='h',
        ),
        migrations.RemoveField(
            model_name='geo',
            name='w',
        ),
    ]
